# Generated by Django 5.1.1 on 2024-10-12 11:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper',
            name='content',
            field=models.TextField(default='Content not available'),
        ),
        migrations.AddField(
            model_name='newspaper',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='newspaper',
            name='publishers',
            field=models.ManyToManyField(related_name='newspapers', to='newspaper_app.redactor'),
        ),
    ]
